"""At-scale θ_d — decision-layer invariance on a HELD-OUT set with LLM-GENERATED classes.

Moves θ_d from *selection* evidence (the 8 calibration scenarios, `measure_theta_d.py`) toward
*bar-meeting* evidence: fresh civil_comments items, classes generated by the NRP LLM at inference
(the deployment form). Pre-registered protocol in `docs/INVARIANCE_FINDINGS.md`.

This is the reproducible ANALYSIS half. It consumes per-member feeder valences captured on the GPU
host (`data/invariance/theta_atscale.json`, produced by the Atlas capture) and computes θ_d — so the
number is auditable from committed code, not just printed once on Atlas.

  θ_d = mean_i |S_A(i) − S_B(i)| / mean_{random i≠j} |S_A(i) − S_A(j)|

where S is the contracted satisfaction scalar and S_A / S_B are the averages over two DISJOINT halves
of the item's generated paraphrase class (split-half: no self-leakage; a conservative upper bound on
the deployed full-class residual).
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
# 9 feeder dims, INDEPENDENT first then the collapsed family — must match the Atlas capture order.
INDEPENDENT = ["physical_harm", "autonomy_respect", "privacy_protection",
               "societal_environmental", "identity_attack"]
FAMILY = ["virtue_care", "fairness_equity", "legitimacy_trust", "epistemic_quality"]
DIMS = INDEPENDENT + FAMILY
N_UNRELATED = 200
SEED = 0


def contract_S(valences) -> float:
    """Contract a 9-dim feeder-valence vector to satisfaction S (family collapses to one factor)."""
    v = {d: float(valences[i]) for i, d in enumerate(DIMS)}
    ind = [v[d] for d in INDEPENDENT]
    fam = float(np.mean([v[d] for d in FAMILY]))
    return float(np.mean(ind + [fam]))


def _norm(t: str) -> str:
    return re.sub(r"\s+", " ", (t or "").strip().lower())


def main() -> None:
    # optional: measure_theta_d_atscale.py <input.json> <output.json>
    inp = sys.argv[1] if len(sys.argv) > 1 else "theta_atscale.json"
    outp_name = sys.argv[2] if len(sys.argv) > 2 else "theta_atscale_result.json"
    data = json.loads((ROOT / "data" / "invariance" / inp).read_text(encoding="utf-8"))
    m = data.get("m", 6)
    items = data["items"]

    # Belt-and-suspenders leakage guard: drop any item whose text hash is in the feeder train set.
    hp = ROOT / "data" / "spectrum" / "feeder_train_hashes.json"
    hset = set(json.loads(hp.read_text())["hashes"]) if hp.exists() else set()
    kept, dropped_leak, refused = [], 0, 0
    for it in items:
        if it.get("refused"):
            refused += 1
            continue
        if hashlib.sha256(_norm(it["text"]).encode()).hexdigest() in hset:
            dropped_leak += 1
            continue
        if len(it["members"]) < m:
            continue
        kept.append(it)

    half = m // 2
    SA, SB, SrawA, SrawB = [], [], [], []
    for it in kept:
        mem = np.array(it["members"], dtype="float64")  # (m, 9)
        a, b = mem[:half], mem[half:m]
        SA.append(contract_S(a.mean(axis=0)))
        SB.append(contract_S(b.mean(axis=0)))
        SrawA.append(contract_S(mem[0]))
        SrawB.append(contract_S(mem[half]))
    SA, SB = np.array(SA), np.array(SB)
    SrawA, SrawB = np.array(SrawA), np.array(SrawB)
    n = len(kept)

    rng = np.random.default_rng(SEED)
    pairs = [(int(i), int(j)) for i, j in rng.integers(0, n, (N_UNRELATED, 2)) if i != j]

    def theta(sa, sb):
        num = float(np.mean(np.abs(sa - sb)))
        den = float(np.mean([abs(sa[i] - sa[j]) for i, j in pairs]))
        return num, den, (num / den if den else float("nan"))

    num, den, th = theta(SA, SB)
    rnum, rden, rth = theta(SrawA, SrawB)

    print(f"items: {len(items)} total · {refused} refused · {dropped_leak} dropped(leak) · {n} used")
    print(f"m={m} (split-half {half}/{half}) · {len(pairs)} unrelated pairs · seed {SEED}\n")
    print(f"RAW (no averaging)        reframe|ΔS|={rnum:.4f}  unrelated|ΔS|={rden:.4f}  "
          f"θ_d_raw={rth:.3f}")
    print(f"MECHANISM (class-average) reframe|ΔS|={num:.4f}  unrelated|ΔS|={den:.4f}  "
          f"θ_d={th:.3f}   {'✓ MEETS ≤0.5' if th <= 0.5 else '✗ above 0.5'}")

    refused_rate = refused / len(items) if items else 0.0
    out = {
        "n_items_total": len(items), "n_used": n, "n_refused": refused,
        "n_dropped_leak": dropped_leak, "refusal_rate": round(refused_rate, 4),
        "m": m, "split_half": half, "seed": SEED, "n_unrelated_pairs": len(pairs),
        "theta_d_raw": round(rth, 4), "theta_d_mechanism": round(th, 4),
        "reframe_dev_raw": round(rnum, 4), "reframe_dev_mech": round(num, 4),
        "unrelated_dev": round(den, 4), "meets_target": bool(th <= 0.5),
        "target": 0.5, "class_generator": data.get("generator", "nrp-llm"),
    }
    outp = ROOT / "data" / "invariance" / outp_name
    outp.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"\nwrote {outp}")


if __name__ == "__main__":
    main()
